tavy315_sylius_labels_admin_label:
    resource: |
        section: admin
        alias: tavy315_sylius_labels.label
        templates: '@SyliusAdmin/Crud'
        permission: true
        redirect: update
        grid: tavy315_sylius_labels_admin_label
        vars:
            all:
                templates:
                    form: "@Tavy315SyliusLabelsPlugin/Admin/Label/_form.html.twig"
                    header_title: "@Tavy315SyliusLabelsPlugin/Admin/Label/_headerTitle.html.twig"
            index:
                icon: 'tags'
    type: sylius.resource

tavy315_sylius_admin_ajax_labels_leafs:
    path: /ajax/labels/leafs
    methods: [GET]
    defaults:
        _controller: tavy315_sylius_labels.controller.label:indexAction
        _format: json
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findAllWithTranslation
                arguments:
                    - "expr:service('sylius.context.locale').getLocaleCode()"
